// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHqnTfRUhy06kZDpafGy9ln22yg0jBC44',
    appId: '1:637540062991:web:f2a35a87288710d73e507a',
    messagingSenderId: '637540062991',
    projectId: 'redwine-e5dfd',
    authDomain: 'redwine-e5dfd.firebaseapp.com',
    storageBucket: 'redwine-e5dfd.appspot.com',
    measurementId: 'G-X58H5JXVEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN1B3cW4rqLycII6IycNNZR9mf53IfNSg',
    appId: '1:637540062991:android:3bb368f6575afe7d3e507a',
    messagingSenderId: '637540062991',
    projectId: 'redwine-e5dfd',
    storageBucket: 'redwine-e5dfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi-4uYMyLpAvji2LXo_8vV5x7CbH9OTZI',
    appId: '1:637540062991:ios:d5b1a7043f9d9d343e507a',
    messagingSenderId: '637540062991',
    projectId: 'redwine-e5dfd',
    storageBucket: 'redwine-e5dfd.appspot.com',
    iosBundleId: 'com.example.redWine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi-4uYMyLpAvji2LXo_8vV5x7CbH9OTZI',
    appId: '1:637540062991:ios:b1339475405326793e507a',
    messagingSenderId: '637540062991',
    projectId: 'redwine-e5dfd',
    storageBucket: 'redwine-e5dfd.appspot.com',
    iosBundleId: 'com.example.redWine.RunnerTests',
  );
}
